# This is the hw.tcl file for 'stft_v1_my_system'
# Generated by High Level Design Compiler for Intel(R) FPGAs 

package require -exact qsys 14.1

# module stft_v1_my_system
set_module_property NAME stft_v1_my_system
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property GROUP "DSP Builder Advanced"
set_module_property DISPLAY_NAME stft_v1_my_system
set_module_property EDITABLE false

# filesets
add_fileset DSPBA_QUARTUS_SYNTH QUARTUS_SYNTH quartus_synth_callback
set_fileset_property DSPBA_QUARTUS_SYNTH TOP_LEVEL stft_v1_my_system

proc quartus_synth_callback {entity_name} {
	add_fileset_file "dspba_library_ver.sv" SYSTEM_VERILOG PATH "../Libraries/sv/base/dspba_library_ver.sv"
	add_fileset_file "stft_v1_my_system_safe_path_flat_ver.sv" SYSTEM_VERILOG PATH "stft_v1_my_system_safe_path_flat_ver.sv"
	add_fileset_file "stft_v1_my_system_safe_path_flat.vhd" VHDL PATH "stft_v1_my_system_safe_path_flat.vhd"
	add_fileset_file "stft_v1_my_system.sv" SYSTEM_VERILOG PATH "stft_v1_my_system.sv"
	add_fileset_file "stft_v1_my_system_Demux_Normalize.sv" SYSTEM_VERILOG PATH "stft_v1_my_system_Demux_Normalize.sv"
	add_fileset_file "stft_v1_my_system_Downscale_1.sv" SYSTEM_VERILOG PATH "stft_v1_my_system_Downscale_1.sv"
	add_fileset_file "stft_v1_my_system_Downscale_2.sv" SYSTEM_VERILOG PATH "stft_v1_my_system_Downscale_2.sv"
	add_fileset_file "stft_v1_my_system_FFT.sv" SYSTEM_VERILOG PATH "stft_v1_my_system_FFT.sv"
	add_fileset_file "stft_v1_my_system_IFFT.sv" SYSTEM_VERILOG PATH "stft_v1_my_system_IFFT.sv"
	add_fileset_file "stft_v1_my_system_Mux_Windowing.sv" SYSTEM_VERILOG PATH "stft_v1_my_system_Mux_Windowing.sv"
}
add_fileset DSPBA_SIM_VERILOG SIM_VERILOG sim_verilog_callback
set_fileset_property DSPBA_SIM_VERILOG TOP_LEVEL stft_v1_my_system

proc sim_verilog_callback {entity_name} {
	add_fileset_file "dspba_library_ver.sv" SYSTEM_VERILOG PATH "../Libraries/sv/base/dspba_library_ver.sv"
	add_fileset_file "stft_v1_my_system_safe_path_flat_ver.sv" SYSTEM_VERILOG PATH "stft_v1_my_system_safe_path_flat_ver.sv"
	add_fileset_file "stft_v1_my_system_safe_path_flat.vhd" VHDL PATH "stft_v1_my_system_safe_path_flat.vhd"
	add_fileset_file "stft_v1_my_system.sv" SYSTEM_VERILOG PATH "stft_v1_my_system.sv"
	add_fileset_file "stft_v1_my_system_Demux_Normalize.sv" SYSTEM_VERILOG PATH "stft_v1_my_system_Demux_Normalize.sv"
	add_fileset_file "stft_v1_my_system_Downscale_1.sv" SYSTEM_VERILOG PATH "stft_v1_my_system_Downscale_1.sv"
	add_fileset_file "stft_v1_my_system_Downscale_2.sv" SYSTEM_VERILOG PATH "stft_v1_my_system_Downscale_2.sv"
	add_fileset_file "stft_v1_my_system_FFT.sv" SYSTEM_VERILOG PATH "stft_v1_my_system_FFT.sv"
	add_fileset_file "stft_v1_my_system_IFFT.sv" SYSTEM_VERILOG PATH "stft_v1_my_system_IFFT.sv"
	add_fileset_file "stft_v1_my_system_Mux_Windowing.sv" SYSTEM_VERILOG PATH "stft_v1_my_system_Mux_Windowing.sv"
}
add_fileset DSPBA_SIM_VHDL SIM_VHDL sim_vhdl_callback
set_fileset_property DSPBA_SIM_VHDL TOP_LEVEL stft_v1_my_system

proc sim_vhdl_callback {entity_name} {
	add_fileset_file "dspba_library_ver.sv" SYSTEM_VERILOG PATH "../Libraries/sv/base/dspba_library_ver.sv"
	add_fileset_file "stft_v1_my_system_safe_path_flat_ver.sv" SYSTEM_VERILOG PATH "stft_v1_my_system_safe_path_flat_ver.sv"
	add_fileset_file "stft_v1_my_system_safe_path_flat.vhd" VHDL PATH "stft_v1_my_system_safe_path_flat.vhd"
	add_fileset_file "stft_v1_my_system.sv" SYSTEM_VERILOG PATH "stft_v1_my_system.sv"
	add_fileset_file "stft_v1_my_system_Demux_Normalize.sv" SYSTEM_VERILOG PATH "stft_v1_my_system_Demux_Normalize.sv"
	add_fileset_file "stft_v1_my_system_Downscale_1.sv" SYSTEM_VERILOG PATH "stft_v1_my_system_Downscale_1.sv"
	add_fileset_file "stft_v1_my_system_Downscale_2.sv" SYSTEM_VERILOG PATH "stft_v1_my_system_Downscale_2.sv"
	add_fileset_file "stft_v1_my_system_FFT.sv" SYSTEM_VERILOG PATH "stft_v1_my_system_FFT.sv"
	add_fileset_file "stft_v1_my_system_IFFT.sv" SYSTEM_VERILOG PATH "stft_v1_my_system_IFFT.sv"
	add_fileset_file "stft_v1_my_system_Mux_Windowing.sv" SYSTEM_VERILOG PATH "stft_v1_my_system_Mux_Windowing.sv"
}

# interfaces
# Interface clock
add_interface clock clock end
set_interface_property clock ENABLED true
add_interface_port clock clk clk Input 1

# Interface clock_reset
add_interface clock_reset reset end
set_interface_property clock_reset ENABLED true
set_interface_property clock_reset ASSOCIATED_CLOCK ""
set_interface_property clock_reset synchronousEdges NONE
add_interface_port clock_reset areset reset Input 1

# Interface stft_v1_my_system_Demux_Normalize_ChannelOut_x
add_interface stft_v1_my_system_Demux_Normalize_ChannelOut_x conduit end
set_interface_assignment stft_v1_my_system_Demux_Normalize_ChannelOut_x "ui.blockdiagram.direction" OUTPUT
set_interface_property stft_v1_my_system_Demux_Normalize_ChannelOut_x ENABLED true
add_interface_port stft_v1_my_system_Demux_Normalize_ChannelOut_x qv_s valid Output 1
set_port_property qv_s VHDL_TYPE STD_LOGIC_VECTOR
add_interface_port stft_v1_my_system_Demux_Normalize_ChannelOut_x q0_re data_0 Output 16
add_interface_port stft_v1_my_system_Demux_Normalize_ChannelOut_x q0_im data_1 Output 16
add_interface_port stft_v1_my_system_Demux_Normalize_ChannelOut_x qc_s channel Output 8

# Interface stft_v1_my_system_Mux_Windowing_ChannelIn_x
add_interface stft_v1_my_system_Mux_Windowing_ChannelIn_x conduit end
set_interface_property stft_v1_my_system_Mux_Windowing_ChannelIn_x ENABLED true
add_interface_port stft_v1_my_system_Mux_Windowing_ChannelIn_x v_s valid Input 1
set_port_property v_s VHDL_TYPE STD_LOGIC_VECTOR
add_interface_port stft_v1_my_system_Mux_Windowing_ChannelIn_x d0_re data_0 Input 16
add_interface_port stft_v1_my_system_Mux_Windowing_ChannelIn_x d0_im data_1 Input 16
add_interface_port stft_v1_my_system_Mux_Windowing_ChannelIn_x c_s channel Input 8
